sudo: required
services:
  - docker

before_install:
  - docker build -t nhuhai/online-order -f Dockerfile.dev .

script:
  - docker run -e CI=true nhuhai/online-order npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "online-order-3"
  env: "OnlineOrder3-env"
  bucket_name: "elasticbeanstalk-us-east-1-339579644962"
  bucket_path: "online-order-3"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY